// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_-VG62D1tAY56-LSaY7-kGFowUskMEA',
    appId: '1:118012302682:web:d1bdfa0b3a1eed1e5b8f63',
    messagingSenderId: '118012302682',
    projectId: 'the-closure-704fe',
    authDomain: 'the-closure-704fe.firebaseapp.com',
    storageBucket: 'the-closure-704fe.appspot.com',
    measurementId: 'G-DDX69QJPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDinnJHCNW4IuoKNa4zQjXkiVALStUNkNA',
    appId: '1:118012302682:android:c469873b6256b02c5b8f63',
    messagingSenderId: '118012302682',
    projectId: 'the-closure-704fe',
    storageBucket: 'the-closure-704fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsso24QamNJY4YuJ43K1U_0dIkm6PNaPY',
    appId: '1:118012302682:ios:671a30fb24d3024a5b8f63',
    messagingSenderId: '118012302682',
    projectId: 'the-closure-704fe',
    storageBucket: 'the-closure-704fe.appspot.com',
    iosBundleId: 'com.example.notiyExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsso24QamNJY4YuJ43K1U_0dIkm6PNaPY',
    appId: '1:118012302682:ios:671a30fb24d3024a5b8f63',
    messagingSenderId: '118012302682',
    projectId: 'the-closure-704fe',
    storageBucket: 'the-closure-704fe.appspot.com',
    iosBundleId: 'com.example.notiyExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK_-VG62D1tAY56-LSaY7-kGFowUskMEA',
    appId: '1:118012302682:web:630ba8e9579c68235b8f63',
    messagingSenderId: '118012302682',
    projectId: 'the-closure-704fe',
    authDomain: 'the-closure-704fe.firebaseapp.com',
    storageBucket: 'the-closure-704fe.appspot.com',
    measurementId: 'G-1H6N097YDX',
  );
}
